name: ashot
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^2.1.0
  cloud_firestore: ^0.13.3
  cupertino_icons: ^0.1.3
  dartz: ^0.9.1
  firebase_core: ^0.4.3+3
  firebase_auth: ^0.15.4
  firebase_database: ^3.1.5
  flushbar: ^1.10.4
  flutter_bloc: ^4.0.0
  freezed_annotation: ^0.7.1
  get_it: ^4.0.2
  google_sign_in: ^4.4.6
  injectable: ^0.4.0
  kt_dart: ^0.7.0
  styled_widget: ^0.2.1
  flutter_hooks: ^0.9.0
  rxdart: ^0.24.1
  uuid: ^2.0.4
  sliding_up_panel: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.1.1
  build_runner:
  freezed: ^0.10.8
  auto_route_generator: ^0.3.2
  injectable_generator: ^0.4.0
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true
